### ISSUE TITLE
Hey Boy i found an error in program 2 here below is the corrected code for program 2  please correct your code fast and asap... 

### ISSUE THREAD

**Issue by Ujju-27** [dakshbamola/compiler_design#2]
%{
	int count = 0;
%}

%%
[a-zA-Z_][a-zA-Z0-9_]* {count++;printf("\n%s is Valid Identifier\n", yytext);}
[a-zA-z_] {printf("\nInValid Identifier");}
%%

int yywrap(){}

int main(){
	printf("Enter the Sentence: ");
	yylex();
	printf("Total number of valid Identifier = %d\n", count);
	return 0;
}

**Comment by dakshbamola** [comment]
Please comment it on the line in which  you see an error
